name: Update Jokes Card SVG

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate SVG from Vercel API
        run: |
          mkdir -p assets
          curl -s "https://readme-jokes.vercel.app/api?bgColor=%23e6ddd8&borderColor=%23997967&qColor=%23ab8c7b&aColor=%23997967&textColor=%23997967&codeColor=%23997967" \
            -o assets/jokesCard.svg

      - name: Commit SVG to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/jokesCard.svg
          git commit -m "Update Jokes card SVG" || echo "No changes"
          git push
