name: Update Profile Gotchi SVG

on:
  schedule:
    - cron: '0 0 * * *' # Updates daily at 00:00 UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-pet:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Pet ðŸ‘¾
        uses: ThanhNguyxn/Git-Gotchi@main
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          username: ${{ github.repository_owner }}
          timezone: 'America/New_York'
          background_theme: 'minimal'
          show_level: 'true'
          
      - name: Commit SVG to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/profileGotchi.svg
          git commit -m "Update Profile Gotchi SVG" || exit 0
          git push
