name: Update WakaTime Rank SVG

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate SVG from Vercel API
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -s "https://wakatime-readme-stats.vercel.app/api/wakatimeStats?username=$GITHUB_ACTOR&api_key=$WAKATIME_API_KEY&github_token=$GITHUB_TOKEN&default_source=github&components=1&show_header=false&bg_color=e6ddd8&text_color=997967&logo_color=fcf9f2&border_color=ab8c7b&border_width=2&border_radius=10&component1_type=rank&component1_rank_color=fcf9f2&mode=progress" \
            -o assets/wakatimeRank.svg

      - name: Commit SVG to repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/wakatimeRank.svg
          git commit -m "Update WakaTime rank SVG" || echo "No changes"
          git push
